<?php

use App\Http\Controllers\LoginController;
use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

// TO`DO: I don't think we should be using this, it was auto generated by sanctum
Route::get('/user', function (Request $request) {
    return $request->user();
})->middleware('auth:sanctum');

Route::post('/login',  [LoginController::class, 'authenticate']);

Route::post('/createTestUser', function (Request $request) {
    $user = new User();
    $user->name = 'test';
    $user->password = Hash::make('password');
    $user->email = 'test@example.com';
    $user->save();

    return response()->json(['message' => 'Test user created successfully!'], 201);
});

Route::get('/ping', function (Request $request) {
    return phpinfo();
});

Route::get('/ping_debug', function (Request $request) {
    return xdebug_info();
});
